**REGRESSION  :---->>  
type of regression :-
1. linear regression 
2.polynomial ---- when due to 1 factor there is a exponential change in outcome.
3. Logistic
slashml.blogspot.com   ----------------website.**

# DATA ---> CLEANING
              ---> RECYCLE
              ---->AUTO FILL
 These all operations called data pre processing (means we convert data into a correct format.) .
 In real world ,this process called data engineering.

In [0]:
import pandas as pd


In [0]:
#reading csv file from url
df = pd.read_csv("http://13.234.66.67/summer19/datasets/info.csv")

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [0]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [0]:
x = df.iloc[:,0:].values    # if we don't use values then it returns the index header also.now after using this we find the oupput without header.
x

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

# pandas is very similar to sql.

In [0]:
# now here we mainly focus on the column where we have missing values.
# removing missing value or replacing missing value with some relevant data .
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [0]:
from sklearn.preprocessing import Imputer   #preprocseeing is a classs in scikit library which is used to deal with this type of data.
imp = Imputer(missing_values='NaN',axis = 0,strategy ='mean')        #axis is basically used for column orientation  ,  only used to deal with missing values in columns
#strategy is basically used to replace missing values by their coloumn mean ,medician etc.

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
impute = imp.fit(x[:,1:3])    #this is only fitting of columns that we want to process.

In [0]:
#time for transforming the fitted columns
x[:,1:3] = impute.transform(x[:,1:3])      #transform used to get data and fit is used for getting the schema where we apply this process.


In [0]:
x                          #here we replace missing values with mean because we use "strategy = mean"


array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 63777.77777777778, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 38.77777777777778, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

**Imputer is used for replacing missing values --only numerical values.we have data here that contain string values(like country) and we know that ML classifier can not deal with the string values . so we need to label it with integer or float values.**

In [0]:
#string label int /float
from sklearn.preprocessing import LabelEncoder

In [0]:
cont = LabelEncoder()    #this is for country  labelling


In [0]:
#now apply column first in this LabelEn
x[:,0] = cont.fit_transform(x[:,0])    #about country column , that we need for labelling

In [0]:
x       # the output here shows integer value in the column of country instead of string values

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# labelling last column --->beacause it also contain string value as yes, no
p=LabelEncoder()
x[:,3] = p.fit_transform(x[:,3])

In [0]:
x

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 63777.77777777778, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.77777777777778, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

if we apply any algo.
if we apply KNN in this , then we know that KNN used distance formula . then in distance formula when we subtracting any label numberr with 0 , then the ouput will become that 0 has no value and the non-zero nom have some value acc. to their values like 0<1<2 ,,but actual we don't want that tha value of any no. degrading ...because 0,1,2, reprsents country in real time , so we don't degarding their values. by overcoming from this situation we divide here country into category : -------------- as it shows that we any row contain france then it shows 1,0,0 means france is present and all others are absent. 
france    |     spain  | germany
1             |     0          | 0
0             |     1          |0
 0            |     0           |0
this is known as encoding .

In [0]:
# now encoding first column  ----- making subcolumn of first column .
#feature scaling --------------????????????????????
from sklearn.preprocessing import OneHotEncoder


In [0]:
 firstcl  =  OneHotEncoder(categorical_features =[0])          #column number   #identifying exact column number where we want to make category
 x = firstcl.fit_transform(x).toarray()         #we here pass full data (x)   because we already give the specific column that we want
#toarray because we convert categories into array


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
x.astype(int)
x


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04, 