# Random forest ----->>  

In [0]:
import pandas as pd

In [0]:
#loading data
df = pd.read_csv("http://13.234.66.67/summer19/datasets/social.csv")

In [6]:
#print schema
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [7]:
df.head()    #top 5 rows

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [0]:
# removing user iD
filterdata = df.iloc[0:,1:]

In [9]:
filterdata.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [0]:
#filterdata = df.iloc[0:,2:]     ---->>> this is because it needs of label encoding for labeling male and female .
# so here we removed the column that require label encoding
filterdata = df.iloc[0:,2:].values

# FEATURE SCALING --> similar range of data is used in this 
eg - >  age =19 and salaary 1900000 
            both are not out of range because salary haave more priority here
            so by the use of this , we used the data within our range 
            

In [0]:
#now we can apply training test
features = filterdata[0:,0:2]

In [0]:
#label finding
label = filterdata[0:,2]

In [0]:
# TRAINING AND TESTING 
from sklearn.model_selection import train_test_split

In [0]:
X ,x,Y,y = train_test_split(features , label , test_size=0.2)

In [0]:
# now apply feature scaling 
from sklearn.preprocessing import StandardScaler

# make this a habit --> on every datasets , first we check label encoding , dummy variable , --onhot encoding , now divide in train and test and then apply  features scaling then add any classifier which you want.


In [0]:
sc = StandardScaler()

In [0]:
#apply scaling in training data only  
X = sc.fit_transform(X)   # X is data after feature scale , when it goes to classifier then it matches with the label and get train . so here we used fit_transform.
#and for testing data we only fit not transform

In [18]:
X

array([[-0.49375545, -0.84465936],
       [ 0.17493392,  0.22631588],
       [ 1.89442087, -0.6709877 ],
       [-0.30270135, -1.36567435],
       [-1.73560714, -0.61309715],
       [ 0.36598802, -0.46837076],
       [ 0.65256918, -1.39461962],
       [ 0.07940686, -0.81571408],
       [-0.3982284 ,  1.29729113],
       [ 0.27046097,  0.02369895],
       [-0.49375545, -0.55520659],
       [-0.30270135,  0.13948005],
       [-0.97139072, -0.32364438],
       [ 1.4167856 ,  0.97889308],
       [ 1.03467739, -0.14997272],
       [-0.2071743 , -0.52626132],
       [ 0.27046097,  0.05264422],
       [ 0.27046097, -0.2946991 ],
       [-0.11164724,  0.02369895],
       [ 0.07940686,  0.02369895],
       [-0.3982284 , -1.30778379],
       [ 2.08547497,  0.37104227],
       [ 1.32125855,  1.26834585],
       [-0.11164724,  0.13948005],
       [ 0.07940686,  0.13948005],
       [-0.30270135, -0.93149519],
       [-0.68480956,  0.54471393],
       [ 0.07940686, -0.26575382],
       [ 0.74809623,

In [0]:
# testing data scaling
from sklearn.preprocessing import StandardScaler
x=sc.transform(x)

In [20]:
type(x)

numpy.ndarray

In [0]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier  #ensemble = by repitation of any things, it trained out data


In [0]:
# calling random forest with number of decision tree .... first we make forests of tree and then multiple tree or best trained tree combined to make our result.
rclf  = RandomForestClassifier(n_estimators=20)

In [0]:
# now training
trained = rclf.fit(X,Y)

In [0]:
#now predicting
output = trained.predict(x)

In [25]:
y    #actual

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [26]:
output #predicted

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

# SUMMARY 
supervised --> label encoding , onehot , train test  , scaling


# COMPUTER VISION  ------------------------------------->>>>>>>>>
 we will give eyes to the computer and we give mind by supervised or neural network technology. By doing visualization it will take input and on the behalf of that  it will train the datasets. we will need of camera for doing this work.
 we will take  data by  -  images , videos , gif , animated video , emoji.
---->> image - collection of number of rows and columns. More the rows , more the heights and the More the columns , more the widths . 
------>>pixel can be RGB and BGR(value range from 0-255).when all pixels are 0 then it means black and when the all pixels are 255 means white. if we want blue color then in BGR er do 255,0,0. 

# ques.    write a code that sysetm should tell major color of picture means in each BGR and RGB check the pixels of each cell and detct the color with major occurance.


In [27]:
import numpy as np
np.zeros((400,300))     #400 and 300 are dimesnions which  means 400 = rows and 300 = colmns

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
#when we save it and view by image viewer or by paint , it will show black color image 
# and for white color images :-
np.full((400,300),255)    

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]])

In [0]:
# when we will do maximm zoom of image ,the smallest unit of image will come is pixel. and the color is from BGR


#IMAGE MANAGEMENT:- 
1. GAN - powerful libraries to process images. 
2. openCV   library in c++.  also work by using python.
both are image processing engine.
for doing this , we will use javascript code for colab to access camera.
now on REDHAT:-
sudo pip3 install opencv-contrib-python
sudo pip3 install numpy
we will not be able to do work on colabs and aws for this.

In [0]:
import cv2

In [30]:
#checking the version
cv2.__version__

'3.4.3'

In [0]:
#image reading
 img = cv2.imread('cofee.jpg')
 # or we also upload the image .

In [0]:
img

In [33]:
type(img)

NoneType

In [34]:
#print shape        #give hieght , width , color channel meams BGR,RGB. when ch =0 mean black/white
img.shape

AttributeError: ignored

In [0]:
#we can also share image using socket programming.
#opencv supports BGR 
#GAN supports RGB
#when we open image it will open in infinte loop and infinite loop is an imageviewer.
#to display image
cv2.imshow('cofee' , img)                       #('---') <-- windowname like in window we save it as cofee.jpg.
# in colabs and aws here it show error beacuse they both will noy supports window function
#wait for windows to close
cv2.waitKey(30)    #hold for 30 milli or micro seconds
cv2.waitKey(0)      #hold for infinite times.






In [0]:
from google.colab.patches import cv2_imshow
cv2.imshow('cofee' , img) 

In [0]:
from google.colab.patches import cv2_imshow

In [0]:
!curl -o logo.png https://colab.research.google.com/img/colab_favicon_256px.png
import cv2
img = cv2.imread('cofee.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

In [0]:
#from this we will show our image here
import matplotlib.pyplot as plt

In [0]:
plt.imshow(img)

# we load the image , there are 3 properties : -
1. image name
2. image properties
# 3 parameters are:---
   # 1 means image in same color channel --GRB or RGB
   # 0 means no color channel--black or white or gray image 
   # -1 mainatin image transparency
   eg : -img = cv2.imread('cofee.jpg',0)

In [0]:
img=cv2.imread('cofee.jpg' , 0)
img1=cv2.imread('cofee.jpg' , 0)


In [0]:
cv2.imshow('dog',img)
cv2.imshow('dog1',img)

In [0]:
from google.colab.patches import cv2_imshow

In [0]:
!curl -o logo.png https://colab.research.google.com/img/colab_favicon_256px.png
import cv2
img = cv2.imread('cofee.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)
cv2_imshow(img1)

# if we want a specific rows and columns ---crop

In [0]:
cv2_imshow(img1[45:200,120:250])   #crop image
cv2_imshow(img)    #original images

# ques1 . we want image of 4*4 of the image means compressing images.  and decompress
#ques2 : - !)zoom -area selected -------2) zoom - that area which is not selected .
                  

# *New Section*

In [0]:
'split' in dir(cv2)

In [0]:
#splitting the BGR
x,y,z = cv2.split(img)   #x=blue, y=green , z= red     # BGR
cv2.imshow('cofee',x)
cv2.imshow('cofee1',y)
cv2.imshow('cofee2',z)



In [0]:
from google.colab.patches import cv2_imshow

In [0]:
!curl -o logo.png https://colab.research.google.com/img/colab_favicon_256px.png
import cv2
img = cv2.imread('cofee.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(x)
cv2_imshow(y)
cv2_imshow(z)

In [43]:
#my image
import numpy as np
myimg = np.zeros((512,512))
cv2.show('cofee4',myimg)

AttributeError: ignored

# *if we want to draw any line or any shape within the images*

In [44]:
#to draw line in image
import cv2
img=cv2.imread('cofee.jpg' , 0)
cv2.line(img,(0,0),(200,230),(0,0,255),3)
cv2.rectangle(img , (50,50),(100,110),(255,0,0),2)
cv2.imshow('my',img)

DisabledFunctionError: ignored

In [0]:
from google.colab.patches import cv2_imshow

In [46]:
!curl -o logo.png https://colab.research.google.com/img/colab_favicon_256px.png
import cv2
img = cv2.imread('cofee.jpg', cv2.IMREAD_UNCHANGED)
cv2.imshow(img)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5500  100  5500    0     0  98214      0 --:--:-- --:--:-- --:--:-- 98214


DisabledFunctionError: ignored

In [0]:
from google.colab.patches import cv2_imshow

In [42]:
!curl -o logo.png https://colab.research.google.com/img/colab_favicon_256px.png
import cv2
img = cv2.imread('cofee.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5500  100  5500    0     0  91666      0 --:--:-- --:--:-- --:--:-- 91666


AttributeError: ignored